
project_id = "plksvatjdylpuhjitbfc"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 100000

[functions.square-sync]
verify_jwt = false

[functions.square-cron]
verify_jwt = false

[functions.sync-scheduler]
verify_jwt = false
# schedule = "*/15 * * * *"

[functions.reprocess-venues]
verify_jwt = false

[functions.xero-token-refresh]
verify_jwt = false

[db]
port = 54322
shadow_port = 54320
major_version = 15
